# Generated by Django 2.2.10 on 2020-05-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vowels_used', models.CharField(blank=True, max_length=200, null=True)),
                ('consonants_used', models.CharField(blank=True, max_length=200, null=True)),
                ('guess', models.CharField(blank=True, max_length=200, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
